name: GitHub Actions Demo

on:
  push:
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencias
        run: npm install
      
      - name: Install Playwright
        run: npx playwright install
        
      - name: Install Cucumber
        run: npm install --save-dev @cucumber/cucumber
        
      - name: Execute tests
        run: npx cucumber-js --tags @all
