name: GitHub Actions Demo

on:
  push:
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2
        
      - name: Instalar dependencias
        run: npm install
      
      - name: Ejecutar pruebas
        run: npx cucumber-js --tags @all
